"""initial schema

Revision ID: 3ef586159deb
Revises: 
Create Date: 2026-09-20 09:03:03.820346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ef586159deb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worlds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('UPCOMING', 'ACTIVE', 'ENDED', name='worldstatus', native_enum=False), nullable=False),
    sa.Column('max_countries', sa.Integer(), nullable=False),
    sa.Column('season_length_days', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_worlds')),
    sa.UniqueConstraint('name', name=op.f('uq_worlds_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('language_code', sa.String(length=8), nullable=False),
    sa.Column('current_world_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('ban_reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['current_world_id'], ['worlds.id'], name=op.f('fk_users_current_world_id_worlds'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('world_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('DROUGHT', 'TRADE_BOOM', 'ENERGY_CRISIS', 'STEEL_SHORTAGE', 'OIL_BOOM', 'BUMPER_HARVEST', name='worldeventtype', native_enum=False), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], name=op.f('fk_world_events_world_id_worlds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_world_events'))
    )
    op.create_index(op.f('ix_world_events_world_id'), 'world_events', ['world_id'], unique=False)
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('nation_code', sa.String(length=4), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('tier', sa.Enum('STANDARD', 'ADVANCED', 'ELITE', name='countrytier', native_enum=False), nullable=False),
    sa.Column('treasury', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('score_economic', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('score_military', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('score_territory', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('score_development', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('score_diplomacy', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('occupied_by_id', sa.Integer(), nullable=True),
    sa.Column('occupied_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['occupied_by_id'], ['countries.id'], name=op.f('fk_countries_occupied_by_id_countries'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_countries_owner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], name=op.f('fk_countries_world_id_worlds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_countries')),
    sa.UniqueConstraint('nation_code', 'world_id', name='uq_nation_per_world'),
    sa.UniqueConstraint('owner_id', 'world_id', name='uq_owner_per_world')
    )
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('awarded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_achievements_country_id_countries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], name=op.f('fk_achievements_world_id_worlds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_achievements'))
    )
    op.create_index(op.f('ix_achievements_country_id'), 'achievements', ['country_id'], unique=False)
    op.create_table('combat_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('attacker_country_id', sa.Integer(), nullable=False),
    sa.Column('defender_country_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('winner', sa.String(length=16), nullable=False),
    sa.Column('attacker_power', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('defender_power', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('attacker_losses_summary', sa.String(length=512), nullable=False),
    sa.Column('defender_losses_summary', sa.String(length=512), nullable=False),
    sa.Column('money_looted', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['attacker_country_id'], ['countries.id'], name=op.f('fk_combat_reports_attacker_country_id_countries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['defender_country_id'], ['countries.id'], name=op.f('fk_combat_reports_defender_country_id_countries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], name=op.f('fk_combat_reports_world_id_worlds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_combat_reports'))
    )
    op.create_index(op.f('ix_combat_reports_attacker_country_id'), 'combat_reports', ['attacker_country_id'], unique=False)
    op.create_index(op.f('ix_combat_reports_defender_country_id'), 'combat_reports', ['defender_country_id'], unique=False)
    op.create_table('country_border_policies',
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('ground_status', sa.Enum('CLOSED', 'LIMITED', 'OPEN', name='borderstatus', native_enum=False), nullable=False),
    sa.Column('air_status', sa.Enum('CLOSED', 'LIMITED', 'OPEN', name='borderstatus', native_enum=False), nullable=False),
    sa.Column('naval_status', sa.Enum('CLOSED', 'LIMITED', 'OPEN', name='borderstatus', native_enum=False), nullable=False),
    sa.Column('trade_status', sa.Enum('CLOSED', 'LIMITED', 'OPEN', name='borderstatus', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_country_border_policies_country_id_countries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('country_id', name=op.f('pk_country_border_policies'))
    )
    op.create_table('country_buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('building_type', sa.Enum('STEEL_MINE', 'URANIUM_MINE', 'OIL_WELL', 'REFINERY', 'STEEL_INDUSTRY', 'WIND_PLANT', 'SOLAR_PLANT', 'HYDRO_PLANT', 'NUCLEAR_PLANT', 'FARM', 'RANCH', 'HOSPITAL', 'POLICE_STATION', 'UNIVERSITY', 'GARRISON', 'AIRPORT', 'PORT', 'MISSILE_SILO', 'TANK_FACTORY', 'AIRCRAFT_FACTORY', 'SHIPYARD', 'MISSILE_FACTORY', 'COMMAND_HQ', 'RADAR', 'LAB', 'SPACE_CENTER', name='buildingtype', native_enum=False), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('upgrade_finishes_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_country_buildings_country_id_countries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_country_buildings')),
    sa.UniqueConstraint('country_id', 'building_type', name='uq_country_building')
    )
    op.create_index(op.f('ix_country_buildings_country_id'), 'country_buildings', ['country_id'], unique=False)
    op.create_table('country_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.Enum('STEEL', 'OIL', 'URANIUM', 'FOOD', 'POWER', name='resourcetype', native_enum=False), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('capacity', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_country_resources_country_id_countries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_country_resources')),
    sa.UniqueConstraint('country_id', 'resource_type', name='uq_country_resource')
    )
    op.create_index(op.f('ix_country_resources_country_id'), 'country_resources', ['country_id'], unique=False)
    op.create_table('country_subscriptions',
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Enum('NONE', 'VIP', name='subscriptiontier', native_enum=False), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_country_subscriptions_country_id_countries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('country_id', name=op.f('pk_country_subscriptions'))
    )
    op.create_table('country_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('unit_type', sa.Enum('INFANTRY', 'TANK', 'ARTILLERY', 'FIGHTER', 'BOMBER', 'TRANSPORT_PLANE', 'DESTROYER', 'SUBMARINE', 'CARRIER', 'TRANSPORT_SHIP', 'SHORT_RANGE_MISSILE', 'LONG_RANGE_MISSILE', 'AIR_DEFENSE', name='unittype', native_enum=False), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_country_units_country_id_countries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_country_units')),
    sa.UniqueConstraint('country_id', 'unit_type', name='uq_country_unit')
    )
    op.create_index(op.f('ix_country_units_country_id'), 'country_units', ['country_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('item', sa.Enum('MONEY', 'STEEL', 'OIL', 'URANIUM', 'FOOD', name='ledgeritem', native_enum=False), nullable=False),
    sa.Column('delta', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_ledger_entries_country_id_countries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_entries'))
    )
    op.create_index(op.f('ix_ledger_entries_country_id'), 'ledger_entries', ['country_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_occurred_at'), 'ledger_entries', ['occurred_at'], unique=False)
    op.create_table('market_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('seller_country_id', sa.Integer(), nullable=False),
    sa.Column('buyer_country_id', sa.Integer(), nullable=True),
    sa.Column('offer_resource', sa.Enum('STEEL', 'OIL', 'URANIUM', 'FOOD', 'POWER', name='resourcetype', native_enum=False), nullable=True),
    sa.Column('offer_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('request_resource', sa.Enum('STEEL', 'OIL', 'URANIUM', 'FOOD', 'POWER', name='resourcetype', native_enum=False), nullable=True),
    sa.Column('request_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'COMPLETED', 'CANCELLED', name='listingstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['buyer_country_id'], ['countries.id'], name=op.f('fk_market_listings_buyer_country_id_countries'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seller_country_id'], ['countries.id'], name=op.f('fk_market_listings_seller_country_id_countries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], name=op.f('fk_market_listings_world_id_worlds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_listings'))
    )
    op.create_index(op.f('ix_market_listings_seller_country_id'), 'market_listings', ['seller_country_id'], unique=False)
    op.create_table('statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('author_country_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_country_id'], ['countries.id'], name=op.f('fk_statements_author_country_id_countries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], name=op.f('fk_statements_world_id_worlds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statements'))
    )
    op.create_table('treaties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('country_a_id', sa.Integer(), nullable=False),
    sa.Column('country_b_id', sa.Integer(), nullable=False),
    sa.Column('proposed_by_id', sa.Integer(), nullable=False),
    sa.Column('treaty_type', sa.Enum('NON_AGGRESSION', 'ALLIANCE', name='treatytype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'CANCELLED', 'REJECTED', name='treatystatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['country_a_id'], ['countries.id'], name=op.f('fk_treaties_country_a_id_countries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['country_b_id'], ['countries.id'], name=op.f('fk_treaties_country_b_id_countries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposed_by_id'], ['countries.id'], name=op.f('fk_treaties_proposed_by_id_countries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], name=op.f('fk_treaties_world_id_worlds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_treaties')),
    sa.UniqueConstraint('world_id', 'country_a_id', 'country_b_id', 'treaty_type', name='uq_treaty_pair_type')
    )
    op.create_table('statement_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('reaction', sa.Enum('SUPPORT', 'CONDEMN', name='statementreactiontype', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_statement_reactions_country_id_countries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], name=op.f('fk_statement_reactions_statement_id_statements'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statement_reactions')),
    sa.UniqueConstraint('statement_id', 'country_id', name='uq_reaction_per_country')
    )
    op.create_index(op.f('ix_statement_reactions_country_id'), 'statement_reactions', ['country_id'], unique=False)
    op.create_index(op.f('ix_statement_reactions_statement_id'), 'statement_reactions', ['statement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statement_reactions_statement_id'), table_name='statement_reactions')
    op.drop_index(op.f('ix_statement_reactions_country_id'), table_name='statement_reactions')
    op.drop_table('statement_reactions')
    op.drop_table('treaties')
    op.drop_table('statements')
    op.drop_index(op.f('ix_market_listings_seller_country_id'), table_name='market_listings')
    op.drop_table('market_listings')
    op.drop_index(op.f('ix_ledger_entries_occurred_at'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_country_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_country_units_country_id'), table_name='country_units')
    op.drop_table('country_units')
    op.drop_table('country_subscriptions')
    op.drop_index(op.f('ix_country_resources_country_id'), table_name='country_resources')
    op.drop_table('country_resources')
    op.drop_index(op.f('ix_country_buildings_country_id'), table_name='country_buildings')
    op.drop_table('country_buildings')
    op.drop_table('country_border_policies')
    op.drop_index(op.f('ix_combat_reports_defender_country_id'), table_name='combat_reports')
    op.drop_index(op.f('ix_combat_reports_attacker_country_id'), table_name='combat_reports')
    op.drop_table('combat_reports')
    op.drop_index(op.f('ix_achievements_country_id'), table_name='achievements')
    op.drop_table('achievements')
    op.drop_table('countries')
    op.drop_index(op.f('ix_world_events_world_id'), table_name='world_events')
    op.drop_table('world_events')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('worlds')
    # ### end Alembic commands ###
